language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev"
install: 
  - "pip install ."
script: 
  - "python setup.py test"
after_success:
  - "pip install python-coveralls"
  - "coveralls"